CoreBB.Web/CoreBB.Web/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreBB.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CoreBB.Web.Controllers
{
    [Authorize]
    public class ForumController : Controller
    {
        private CoreBBContext _dbContext;

        public ForumController(CoreBBContext dbContext)
        {
            _dbContext = dbContext;
        }

        private Forum GetForum(Forum model)
        {
            var forum = _dbContext.Forum.SingleOrDefault(f => f.Id == model.Id);
            if (forum == null)
            {
                throw new Exception("Forum does not exist.");
            }

            return forum;
        }

        private Forum GetForum(int Id)
        {
            var forum = _dbContext.Forum.Include(f => f.Owner).SingleOrDefault(f => f.Id == Id);
            if (forum == null)
            {
                throw new Exception("Forum does not exist.");
            }

            return forum;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var forums = _dbContext.Forum.Include(u => u.Owner).ToList();
            return View(forums);
        }

        [HttpGet, Authorize(Roles = Roles.Administrator)]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet, Authorize(Roles = Roles.Administrator)]
        public IActionResult Lock(int Id)
        {
            var forum = GetForum(Id);

            return View(forum);
        }

        public async Task<IActionResult> Lock(Forum model)
        {
            var forum = GetForum(model);

            forum.IsLocked = !forum.IsLocked;
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Detail", new { forum.Id });
        }

        [HttpPost, Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Create(Forum model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid forum information.");
            }

            model.OwnerId = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name).Id;
            model.CreateDateTime = DateTime.Now;
            await _dbContext.Forum.AddAsync(model);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Detail(int Id)
        {
            var forum = GetForum(Id);

            return View(forum);
        }

        [HttpGet, Authorize(Roles = Roles.Administrator)]
        public IActionResult Delete(int Id)
        {
            var forum = GetForum(Id);

            return View(forum);
        }

        [HttpPost, Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Delete(Forum model)
        {
            var forum = GetForum(model);

            _dbContext.Forum.Remove(forum);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet, Authorize(Roles = Roles.Administrator)]
        public IActionResult Edit(int Id)
        {
            var forum = GetForum(Id);

            return View(forum);
        }

        [HttpPost, Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Edit(Forum model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid forum information");
            }

            _dbContext.Forum.Update(model);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

CoreBB.Web/CoreBB.Web/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreBB.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CoreBB.Web.Controllers
{
    public class TopicController : Controller
    {
        private CoreBBContext _dbContext;

        public TopicController(CoreBBContext dbContext)
        {
            _dbContext = dbContext;
        }

        private Topic GetTopic(int Id)
        {
            var topic = _dbContext.Topic.Include(t => t.Owner).Include(t => t.ModifiedByUser).SingleOrDefault(t => t.Id == Id);
            if (topic == null)
            {
                throw new Exception("Topic does not exist.");
            }
            return topic;
        }

        [HttpGet]
        public IActionResult Index(int forumId)
        {
            var forum = _dbContext.Forum.Include(f => f.Owner).SingleOrDefault(f => f.Id == forumId);
            if (forum == null)
            {
                throw new Exception("Forum does not exist.");
            }

            forum.Topic = _dbContext.Topic.Include(t => t.Owner)
                .Where(t => t.ForumId == forum.Id && t.ReplyToTopicId == null).ToList();
            return View(forum);
        }

        [HttpGet]
        public IActionResult Create(int forumId)
        {
            var forum = _dbContext.Forum.SingleOrDefault(f => f.Id == forumId);
            if (forum == null)
            {
                throw new Exception("Forum does not exist.");
            }

            if (forum.IsLocked && !User.IsInRole(Roles.Administrator))
            {
                throw new Exception("This forum is locked.");
            }

            var topic = new Topic { ForumId = forumId };
            return View(topic);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Topic model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid topic information.");
            }

            var user = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name);
            model.OwnerId = user.Id;
            model.PostDateTime = DateTime.Now;
            await _dbContext.Topic.AddAsync(model);
            await _dbContext.SaveChangesAsync();
            model.RootTopicId = model.Id;
            _dbContext.Topic.Update(model);
            await _dbContext.SaveChangesAsync();
                
            return RedirectToAction("Index", new { model.ForumId });
        }

        [HttpGet]
        public IActionResult Detail(int Id)
        {
            var rootTopic = _dbContext.Topic.Include(t => t.Owner).Include(t => t.ModifiedByUser)
                .SingleOrDefault(t => t.Id == Id);
            if (rootTopic == null)
            {
                throw new Exception("Topic does not exist.");
            }

            rootTopic.InverseReplyToTopic = _dbContext.Topic.Include(t => t.Owner).Include(t => t.ModifiedByUser)
                .Where(t => t.RootTopicId == Id && t.ReplyToTopicId != null).ToList();
            return View(rootTopic);
        }

        [HttpGet]
        public IActionResult Reply(int toId)
        {
            var toTopic = _dbContext.Topic.SingleOrDefault(t => t.Id == toId);
            if (toTopic == null)
            {
                throw new Exception("Topic does not exist.");
            }

            var topic = new Topic
            {
                ReplyToTopicId = toTopic.Id,
                RootTopicId = toTopic.RootTopicId,
                ForumId = toTopic.ForumId,
                ReplyToTopic = toTopic
            };

            return View(topic);
        }

        [HttpPost]
        public async Task<IActionResult> Reply(Topic model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid topic information.");
            }


            var user = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name);
            model.OwnerId = user.Id;
            model.PostDateTime = DateTime.Now;
            await _dbContext.Topic.AddAsync(model);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Index", new { forumId = model.ForumId });
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var topic = GetTopic(Id); 

            return View(topic);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Topic model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid information for topic");
            }
            var user = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name);
            model.ModifiedByUserId = user.Id;
            model.ModifyDateTime = DateTime.Now;
            _dbContext.Topic.Update(model);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Index", new { forumId = model.ForumId });
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            var topic = GetTopic(Id); 

            return View(topic);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Topic model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid topic information");
            }
            var topic = _dbContext.Topic.SingleOrDefault(t => t.Id == model.Id);
            IQueryable<Topic> replyTopics;
            if (topic.ReplyToTopicId == null)
            {
                replyTopics = _dbContext.Topic.Where(t => t.RootTopicId == topic.Id);
            }
            else
            {
                replyTopics = _dbContext.Topic.Where(t => t.ReplyToTopicId == topic.Id);
            }

            _dbContext.Topic.Remove(topic);
            _dbContext.Topic.RemoveRange(replyTopics);
            await _dbContext.SaveChangesAsync();
    
            return RedirectToAction("Index", new { forumId = topic.ForumId });
        }
    }
}

CoreBB.Web/CoreBB.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CoreBB.Web.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CoreBB.Web.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private CoreBBContext _dbContext;
        public UserController(CoreBBContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet, Authorize(Roles = Roles.Administrator)]
        public IActionResult Index()
        {
            var users = _dbContext.User.ToList();
            return View(users);
        }

        [AllowAnonymous, HttpGet]
        public async Task<IActionResult> Register()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }

        [AllowAnonymous, HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid registration information.");
            }

            model.Name = model.Name.Trim();
            model.Password = model.Password.Trim();
            model.RepeatPassword = model.RepeatPassword.Trim();

            var targetUser = _dbContext.User
                .SingleOrDefault(u => u.Name.Equals(model.Name, StringComparison.CurrentCultureIgnoreCase));

            if (targetUser != null)
            {
                throw new Exception("User name already exists.");
            }

            if (!model.Password.Equals(model.RepeatPassword))
            {
                throw new Exception("Password are not identical.");
            }

            var hasher = new PasswordHasher<User>();
            targetUser = new User { Name = model.Name, RegisterDateTime = DateTime.Now, Description = model.Description };
            targetUser.PasswordHash = hasher.HashPassword(targetUser, model.Password);

            if (_dbContext.User.Count() == 0)
            {
                targetUser.IsAdministrator = true;
            }

            await _dbContext.User.AddAsync(targetUser);
            await _dbContext.SaveChangesAsync();

            await LogInUserAsync(targetUser);

            return RedirectToAction("Index", "Home");
        }

        private async Task LogInUserAsync(User user)
        {
            var claims = new List<Claim>();
            claims.Add(new Claim(ClaimTypes.Name, user.Name));
            if (user.IsAdministrator)
            {
                claims.Add(new Claim(ClaimTypes.Role, Roles.Administrator));
            }

            var claimsIndentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var claimsPrincipal = new ClaimsPrincipal(claimsIndentity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal);
            user.LastLogInDateTime = DateTime.Now;
            await _dbContext.SaveChangesAsync();
        }

        [AllowAnonymous, HttpGet]
        public async Task<IActionResult> LogIn()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }

        [AllowAnonymous, HttpPost]
        public async Task<IActionResult> LogIn(LogInViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid user information.");
            }

            var targetUser = _dbContext.User.SingleOrDefault(u => u.Name.Equals(model.Name, 
                StringComparison.CurrentCultureIgnoreCase));
            if (targetUser == null)
            {
                throw new Exception("User does not exist");
            }

            var hasher = new PasswordHasher<User>();
            var result = hasher.VerifyHashedPassword(targetUser, targetUser.PasswordHash, model.Password);
            if (result != PasswordVerificationResult.Success)
            {
                throw new Exception("The password is wrong.");
            }

            await LogInUserAsync(targetUser);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Detail(string name)
        {
            var user = _dbContext.User.SingleOrDefault(u => u.Name == name);
            if (user == null)
            {
                throw new Exception($"User '{name}' does not exist.");
            }
            return View(user);
        }

        [HttpGet]
        public IActionResult Edit(string name)
        {
            if (User.Identity.Name != name && !User.IsInRole(Roles.Administrator))
            {
                throw new Exception("Operation is denied.");
            }

            var user = _dbContext.User.SingleOrDefault(u => u.Name == name);
            if (user == null)
            {
                throw new Exception($"User '{name}' does not exist.");
            }

            var model = UserEditViewModel.FromUser(user);
            return View(model);
        }

        public async Task<IActionResult> Edit(UserEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid user information.");
            }

            var user = _dbContext.User
                .SingleOrDefault(u => u.Name.Equals(model.Name, StringComparison.CurrentCultureIgnoreCase));

            if (user == null)
            {
                throw new Exception("User does not exist.");
            }

            if (!string.IsNullOrEmpty(model.Password))
            {
                model.Password = model.Password.Trim();
                model.RepeatPassword = model.RepeatPassword.Trim();
                if (!model.Password.Equals(model.RepeatPassword))
                {
                    throw new Exception("Passwords are not identical.");
                }

                var hasher = new PasswordHasher<User>();
                if (!User.IsInRole(Roles.Administrator))
                {
                    var vr = hasher.VerifyHashedPassword(user, user.PasswordHash, model.CurrentPassword);
                    if (vr != PasswordVerificationResult.Success)
                    {
                        throw new Exception("Please provide correct current password.");
                    }
                }

                user.PasswordHash = hasher.HashPassword(user, model.Password);
            }

            user.Description = model.Description;

            if (User.IsInRole(Roles.Administrator))
            {
                user.IsAdministrator = model.IsAdministrator;
                user.IsLocked = model.IsLocked;
            }

            _dbContext.User.Update(user);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Detail", new { name = user.Name });
        }
    }
}

CoreBB.Web/CoreBB.Web/Views/Shared/_ForumDetail.cshtml
@using CoreBB.Web.Models
@model Forum

<div class="container col-6 offset-3" style="margin-top:120px">
    <div class="card border-info">
        <div class="card-header text-white bg-info">
            <strong>Forum Detail Information</strong>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-striped">
                <tr>
                    <th>Property</th>
                    <th>Value</th>
                </tr>
                <tr>
                    <td><strong>ID</strong></td>
                    <td>@Model.Id</td>
                </tr>
                <tr>
                    <td><strong>Name</strong></td>
                    <td>@Model.Name</td>
                </tr>
                <tr>
                    <td><strong>Owner</strong></td>
                    <td><a asp-action="Detail" asp-controller="User" asp-route-name="@Model.Owner.Name">@Model.Owner.Name</a></td>
                </tr>
                <tr>
                    <td><strong>Description</strong></td>
                    <td>@Model.Description</td>
                </tr>
                <tr>
                    <td><strong>Locked</strong></td>
                    <td><input type="checkbox" asp-for="IsLocked" disabled="disabled" /></td>
                </tr>
                <tr>
                    <td><strong>Create Date</strong></td>
                    <td>@Model.CreateDateTime.ToShortDateString()</td>
                </tr>
                <tr>
                    <td><strong>Operation</strong></td>
                    <td>
                        @if ((string)ViewData["Mode"] == "ShowingDetail")
                        {
                            @if (User.IsInRole(Roles.Administrator))
                            {
                                <a class="btn-sm btn-primary" asp-action="Edit" asp-route-id="@Model.Id">Update</a>
                                <a class="btn-sm btn-primary" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
                                @if (!Model.IsLocked)
                                {
                                    <a class="btn-sm btn-primary" asp-action="Lock" asp-route-id="@Model.Id">Lock</a>
                                }
                                else
                                {
                                    <a class="btn-sm btn-primary" asp-action="Lock" asp-route-id="@Model.Id">UnLock</a>
                                }
                            }
                            <a class="btn-sm btn-success" asp-controller="Topic"
                               asp-action="Create" asp-route-forumid="@Model.Id">Post Topic</a>}
                        @if ((string)ViewData["Mode"] == "ConfirmingDelete")
                        {
                            <h5 style="text-align:center">Warning: All topics in this forum will be also deleted!</h5>
                            <input type="submit" class="btn-sm btn-warning" value="Confirm" />
                        }
                        @if ((string)ViewData["Mode"] == "ConfirmingLock")
                        {
                            @if (!Model.IsLocked)
                            {
                                <h5 style="text-align:center">Warning: In Locked forum users can`t create topics!</h5>
                            }
                            else
                            {
                                <h5 style="text-align:center">Warning: In Unlocked forum users can create topics!</h5>
                            }
                            <input type="submit" class="btn-sm btn-warning" value="Confirm" />
                        }
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

CoreBB.Web/CoreBB.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using CoreBB.Web.Models
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/Content/jQuery/jquery-3.3.1.js"></script>
    <script src="~/Content/Bootstrap/js/bootstrap.js"></script>
    <script src="~/Content/Bootstrap/js/bootstrap.bundle.js"></script>
    <link href="~/Content/Bootstrap/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" asp-action="Index" asp-controller="Home">CoreBB</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Home">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Forum">Forums</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Message">Messages</a>
                </li>
                @if (User.IsInRole(Roles.Administrator))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" 
                           aria-haspopup="true" aria-expanded="false">
                            Manage
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-action="Index" asp-controller="User">Users</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-action="Create" asp-controller="Forum">Create Forum</a>
                        </div>
                    </li>
                }
            </ul>
            <div class="pull-right">
                @if (!User.Identity.IsAuthenticated)
                {
                    <div class="btn-group btn-group-lg">
                        <a class="btn btn-secondary btn-info" asp-controller="User" asp-action="LogIn">Log In</a>
                        <a class="btn btn-secondary btn-info" asp-controller="User" asp-action="Register">Register</a>
                    </div>
                }
                else
                {
                    <div class="btn-group btn-group-lg">
                        <a class="btn btn-secondary btn-info" asp-controller="User" asp-action="Detail"
                           asp-route-name="@User.Identity.Name">My Account</a>
                        <a class="btn btn-secondary btn-info" asp-controller="User" asp-action="Edit"
                           asp-route-name="@User.Identity.Name">Edit</a>
                        <a class="btn btn-secondary btn-info" asp-controller="User" asp-action="LogOut">Log Out</a>
                    </div>
                }
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <hr />
    <footer>
        <p>&copy; 2017 - CoreBB</p>
    </footer>
</body>
</html>

CoreBB.Web/CoreBB.Web/Views/Shared/_MessageIndexing.cshtml
@model CoreBB.Web.Models.Message

@{

}

<td><a asp-controller="User" asp-action="Detail" asp-route-name="@Model.ToUser.Name">@Model.ToUser.Name</a></td>
@if (Model.Content.Length > 20)
{
    <td><a asp-action="Detail" asp-route-id="@Model.Id">@Model.Content.Substring(0, 50)...</a></td>
}
else
{
    <td><a asp-action="Detail" asp-route-id="@Model.Id">@Model.Content</a></td>
}
<td>@Model.SendDateTime.ToString()</td>

CoreBB.Web/CoreBB.Web/Views/Shared/_MessageLayout.cshtml
@model CoreBB.Web.Models.Message

@{
    ViewData["Title"] = "Сообщение";
}

<div class="card border-dark">
    <div class="card-header text-white bg-dark">
        <br />
        From: <a asp-controller="User" asp-action="Detail" asp-route-name="@Model.FromUser.Name">@Model.FromUser.Name</a>
        To: <a asp-controller="User" asp-action="Detail" asp-route-name="@Model.ToUser.Name">@Model.ToUser.Name</a>
    </div>
    <div class="card-body">
        @Model.Content
    </div>
    <div class="card-footer">
        @if ((string)ViewData["Mode"] != "Deleting")
        {
            <a class="btn-sm btn-warning" asp-action="Create" asp-route-tousername="@Model.FromUser.Name">Reply</a>
            <a class="btn-sm btn-danger" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
        }
        else
        {
            <p>Do you want to delete the message?</p>
            <input type="submit" class="btn-sm btn-danger" value="Confirm Delete" />
        }
    </div>
</div>

CoreBB.Web/CoreBB.Web/Views/Shared/_TopicEditing.cshtml
@model CoreBB.Web.Models.Topic
@{
    
}

<div class="container col-6 offset-3" style="margin-top:120px">
    <div class="card border-info">
        <div class="card-header text-white bg-info">
            <strong>@ViewData["Reply"]</strong>
        </div>
        <div class="card-body">
            <div class="form-group">
                <label asp-for="Title">Title *</label>
                <input class="form-control" asp-for="Title" required />
            </div>
            <div class="form-group">
                <label asp-for="Content">Content *</label>
                <textarea class="form-control" style="min-height:120px" asp-for="Content" required></textarea>
            </div>
            @if ((string)ViewData["Mode"] != "Reply")
            {
                <div class="form-group">
                    <span>Lock</span>
                    <input type="checkbox" asp-for="IsLocked" />
                </div>
            }
        </div>
        <div class="card-footer">
            <input type="submit" class="btn-sm btn-success" value="@ViewData["SubmitButtonText"]" />
        </div>
    </div>
</div>

CoreBB.Web/CoreBB.Web/Views/Shared/_TopicReading.cshtml
@using CoreBB.Web.Models
@model Topic

<div class="container" style="padding-top:30px">
    <div class="card border-info">
        <div class="card-header">
            <strong>@Model.Title</strong>
            [Posted by <a asp-controller="User" asp-action="Detail" asp-route-name="@Model.Owner.Name">@Model.Owner.Name</a>
            at @Model.PostDateTime.ToShortDateString()]
            @if (@Model.ModifiedByUserId != null)
            {
                <span>
                    [Modified by <a asp-controller="User" asp-action="Detail" asp-route-name="@(Model.ModifiedByUser?.Name ?? "N/A")">
                        @(Model.ModifiedByUser?.Name ?? "N/A")
                    </a> at @(Model.ModifyDateTime?.ToString() ?? "N/A")]
                </span>
            }
        </div>
        <div class="card-body">
            <p>@Model.Content</p>
        </div>
        <div class="card-footer">
            @if ((string)ViewData["Mode"] != "Deleting")
            {
                @if (!Model.IsLocked || User.IsInRole(Roles.Administrator))
                {
                    <a class="btn-sm btn-success" asp-action="Reply" asp-controller="Topic" asp-route-toid="@Model.Id">Reply</a>
                }
                @if (Model.Owner.Name == User.Identity.Name || User.IsInRole(Roles.Administrator))
                {
                    <a class="btn-sm btn-success" asp-action="Edit" asp-controller="Topic" asp-route-id="@Model.Id">Edit</a>
                    <a class="btn-sm btn-success" asp-action="Delete" asp-controller="Topic" asp-route-id="@Model.Id">Delete</a>
                }
            }
            else
            {
                <p>Do you want delete this topic?</p>
                <input type="submit" class="btn-sm btn-danger" value="Confirm delete" />             
            }
        </div>
    </div>
</div>