CoreBB.Web/CoreBB.Web/Models/LogInViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CoreBB.Web.Models
{
    public class LogInViewModel
    {
        [Required, DisplayName("Name")]
        public string Name { get; set; }

        [Required, DisplayName("Password")]
        public string Password { get; set; }
    }
}

CoreBB.Web/CoreBB.Web/Models/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CoreBB.Web.Models
{
    public class RegisterViewModel
    {
        [Required, DisplayName("Name")]
        public string Name { get; set; }
        [Required, DisplayName("Password")]
        public string Password { get; set; }
        [Required, DisplayName("RepeatPassword")]
        public string RepeatPassword { get; set; }
        [Required, DisplayName("Self-Introduction")]
        public string Description { get; set; }
    }
}

CoreBB.Web/CoreBB.Web/Models/User.cs
using System;
using System.Collections.Generic;

namespace CoreBB.Web.Models
{
    public partial class User
    {
        public User()
        {
            Forum = new HashSet<Forum>();
            MessageFromUser = new HashSet<Message>();
            MessageToUser = new HashSet<Message>();
            TopicModifiedByUser = new HashSet<Topic>();
            TopicOwner = new HashSet<Topic>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string PasswordHash { get; set; }
        public string Description { get; set; }
        public bool IsAdministrator { get; set; }
        public bool IsLocked { get; set; }
        public DateTime RegisterDateTime { get; set; }
        public DateTime LastLogInDateTime { get; set; }

        public ICollection<Forum> Forum { get; set; }
        public ICollection<Message> MessageFromUser { get; set; }
        public ICollection<Message> MessageToUser { get; set; }
        public ICollection<Topic> TopicModifiedByUser { get; set; }
        public ICollection<Topic> TopicOwner { get; set; }
    }
}

CoreBB.Web/CoreBB.Web/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreBB.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CoreBB.Web.Controllers
{
    [Authorize]
    public class MessageController : Controller
    {
        private CoreBBContext _dbContext;

        public MessageController(CoreBBContext dbContext)
        {
            _dbContext = dbContext;
        }

        private Message GetMessage(int Id)
        {
            var message = _dbContext.Message.Include(m => m.FromUser).Include(m => m.ToUser)
                .SingleOrDefault(m => m.Id == Id);

            if (message == null)
            {
                throw new Exception("Message does not exist.");
            }

            return message;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var user = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name);
            var messages = _dbContext.Message.Include(m => m.FromUser).Include(m => m.ToUser)
                .Where(t => t.ToUser.Name == user.Name || t.FromUser.Name == user.Name);

            return View(messages);
        }

        [HttpGet]
        public IActionResult Create(string toUserName)
        {
            var ToUser = _dbContext.User.SingleOrDefault(u => u.Name == toUserName);
            if (ToUser == null)
            {
                throw new Exception("User does not exist.");
            }
            var message = new Message { ToUserId = ToUser.Id, ToUser = ToUser };

            return View(message);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Message model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Information for message is invalid.");
            }

            var FromUser = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name);
            model.FromUserId = FromUser.Id;
            model.SendDateTime = DateTime.Now;
            model.IsRead = false;
            await _dbContext.Message.AddAsync(model);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Index", "Home"); // ---
        } // ---

        [HttpGet]
        public IActionResult Detail(int Id)
        {
            var message = GetMessage(Id);
            var messages = _dbContext.Message
                .Where(m => (m.FromUserId == message.FromUserId && m.ToUserId == message.ToUserId) || (m.FromUserId == message.ToUserId && m.ToUserId == message.FromUserId))
                .OrderBy(m => m.SendDateTime);

            return View(messages);
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            var message = GetMessage(Id);

            return View(message);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Message model)
        {
            _dbContext.Message.Remove(model);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

CoreBB.Web/CoreBB.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CoreBB.Web.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CoreBB.Web.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private CoreBBContext _dbContext;
        public UserController(CoreBBContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet, Authorize(Roles = Roles.Administrator)]
        public IActionResult Index()
        {
            var users = _dbContext.User.ToList();
            return View(users);
        }

        [AllowAnonymous, HttpGet]
        public async Task<IActionResult> Register()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }

        [AllowAnonymous, HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid registration information.");
            }

            model.Name = model.Name.Trim();
            model.Password = model.Password.Trim();
            model.RepeatPassword = model.RepeatPassword.Trim();

            var targetUser = _dbContext.User
                .SingleOrDefault(u => u.Name.Equals(model.Name, StringComparison.CurrentCultureIgnoreCase));

            if (targetUser != null)
            {
                throw new Exception("User name already exists.");
            }

            if (!model.Password.Equals(model.RepeatPassword))
            {
                throw new Exception("Password are not identical.");
            }

            var hasher = new PasswordHasher<User>();
            targetUser = new User { Name = model.Name, RegisterDateTime = DateTime.Now, Description = model.Description };
            targetUser.PasswordHash = hasher.HashPassword(targetUser, model.Password);

            if (_dbContext.User.Count() == 0)
            {
                targetUser.IsAdministrator = true;
            }

            await _dbContext.User.AddAsync(targetUser);
            await _dbContext.SaveChangesAsync();

            await LogInUserAsync(targetUser);

            return RedirectToAction("Index", "Home");
        }

        private async Task LogInUserAsync(User user)
        {
            var claims = new List<Claim>();
            claims.Add(new Claim(ClaimTypes.Name, user.Name));
            if (user.IsAdministrator)
            {
                claims.Add(new Claim(ClaimTypes.Role, Roles.Administrator));
            }

            var claimsIndentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var claimsPrincipal = new ClaimsPrincipal(claimsIndentity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal);
            user.LastLogInDateTime = DateTime.Now;
            await _dbContext.SaveChangesAsync();
        }

        [AllowAnonymous, HttpGet]
        public async Task<IActionResult> LogIn()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }

        [AllowAnonymous, HttpPost]
        public async Task<IActionResult> LogIn(LogInViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid user information.");
            }

            var targetUser = _dbContext.User.SingleOrDefault(u => u.Name.Equals(model.Name, 
                StringComparison.CurrentCultureIgnoreCase));
            if (targetUser == null)
            {
                throw new Exception("User does not exist");
            }

            var hasher = new PasswordHasher<User>();
            var result = hasher.VerifyHashedPassword(targetUser, targetUser.PasswordHash, model.Password);
            if (result != PasswordVerificationResult.Success)
            {
                throw new Exception("The password is wrong.");
            }

            await LogInUserAsync(targetUser);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Detail(string name)
        {
            var user = _dbContext.User.SingleOrDefault(u => u.Name == name);
            if (user == null)
            {
                throw new Exception($"User '{name}' does not exist.");
            }
            return View(user);
        }

        [HttpGet]
        public IActionResult Edit(string name)
        {
            if (User.Identity.Name != name && !User.IsInRole(Roles.Administrator))
            {
                throw new Exception("Operation is denied.");
            }

            var user = _dbContext.User.SingleOrDefault(u => u.Name == name);
            if (user == null)
            {
                throw new Exception($"User '{name}' does not exist.");
            }

            var model = UserEditViewModel.FromUser(user);
            return View(model);
        }

        public async Task<IActionResult> Edit(UserEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid user information.");
            }

            var user = _dbContext.User
                .SingleOrDefault(u => u.Name.Equals(model.Name, StringComparison.CurrentCultureIgnoreCase));

            if (user == null)
            {
                throw new Exception("User does not exist.");
            }

            if (!string.IsNullOrEmpty(model.Password))
            {
                model.Password = model.Password.Trim();
                model.RepeatPassword = model.RepeatPassword.Trim();
                if (!model.Password.Equals(model.RepeatPassword))
                {
                    throw new Exception("Passwords are not identical.");
                }

                var hasher = new PasswordHasher<User>();
                if (!User.IsInRole(Roles.Administrator))
                {
                    var vr = hasher.VerifyHashedPassword(user, user.PasswordHash, model.CurrentPassword);
                    if (vr != PasswordVerificationResult.Success)
                    {
                        throw new Exception("Please provide correct current password.");
                    }
                }

                user.PasswordHash = hasher.HashPassword(user, model.Password);
            }

            user.Description = model.Description;

            if (User.IsInRole(Roles.Administrator))
            {
                user.IsAdministrator = model.IsAdministrator;
                user.IsLocked = model.IsLocked;
            }

            _dbContext.User.Update(user);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Detail", new { name = user.Name });
        }
    }
}

CoreBB.Web/CoreBB.Web/Views/User/Detail.cshtml
@using CoreBB.Web.Models
@model User
@{
    ViewBag.Title = "User Detail";
}

<div class="container col-6 offset-3" style="margin-top:120px">
    <div class="card border-info">
        <div class="card-header text-white bg-info">
            <strong>User Detail Information</strong>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-striped">
                <tr>
                    <th>Property</th>
                    <th>Value</th>
                </tr>
                <tr>
                    <td><strong>ID</strong></td>
                    <td>@Model.Id</td>
                </tr>
                <tr>
                    <td><strong>Name</strong></td>
                    <td>@Model.Name</td>
                </tr>
                <tr>
                    <td><strong>Description</strong></td>
                    <td>@Model.Description</td>
                </tr>
                <tr>
                    <td><strong>Administrator</strong></td>
                    <td><input type="checkbox" asp-for="IsAdministrator" disabled="disabled" /></td>
                </tr>
                <tr>
                    <td><strong>Locked</strong></td>
                    <td><input type="checkbox" asp-for="IsLocked" disabled="disabled" /></td>
                </tr>
                <tr>
                    <td><strong>Register Date</strong></td>
                    <td>@Model.RegisterDateTime.ToShortDateString()</td>
                </tr>
                <tr>
                    <td><strong>Last Login</strong></td>
                    <td>@Model.LastLogInDateTime.ToShortDateString()</td>
                </tr>
                @if (User.Identity.Name != Model.Name)
                {
                    <tr>
                        <td><strong>Operations</strong></td>
                        <td>
                            <a class="btn-sm btn-warning" asp-controller="Message" , asp-action="Create"
                               asp-route-tousername="@Model.Name">Send Message</a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

CoreBB.Web/CoreBB.Web/Views/User/Edit.cshtml
@using CoreBB.Web.Models
@model UserEditViewModel
@{
    ViewBag.Title = "Update User";
}

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="Name" />
    <input type="hidden" asp-for="RegisterDateTime" />
    <input type="hidden" asp-for="LastLogInDateTime" />
    <div class="container col-6 offset-3" style="margin-top:120px">
        <div class="card border-info">
            <div class="card-header text-white bg-info">
                <strong>Update User</strong>
            </div>
            <div class="card-body">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>Property</th>
                        <th>Value</th>
                    </tr>
                    <tr>
                        <td><strong>ID</strong></td>
                        <td>@Model.Id</td>
                    </tr>
                    <tr>
                        <td><strong>Name</strong></td>
                        <td>@Model.Name</td>
                    </tr>
                    @if (!User.IsInRole(Roles.Administrator))
                    {
                        <tr>
                            <td>
                                <strong>Current Password</strong>
                            </td>
                            <td>
                                <input class="form-control" type="password" asp-for="CurrentPassword" />
                            </td>
                        </tr>

                    }
                    <tr>
                        <td>
                            <strong>New Password</strong>
                        </td>
                        <td>
                            <input class="form-control" type="password" asp-for="Password" />
                        </td>
                    </tr>
                    <tr>
                        <td><strong>Repeat New Password</strong></td>
                        <td><input class="form-control" type="password" asp-for="RepeatPassword" /></td>
                    </tr>
                    <tr>
                        <td><strong>Description</strong></td>
                        <td><textarea class="form-control" asp-for="Description"></textarea></td>
                    </tr>
                    @if (User.IsInRole(Roles.Administrator))
                    {
                        <tr>
                            <td><strong>Administrator</strong></td>
                            <td><input type="checkbox" asp-for="IsAdministrator" /></td>
                        </tr>
                        <tr>
                            <td><strong>Locked</strong></td>
                            <td><input type="checkbox" asp-for="IsLocked" /></td>
                        </tr>
                    }
                    <tr>
                        <td><strong>Register Date</strong></td>
                        <td>@Model.RegisterDateTime.ToShortDateString()</td>
                    </tr>
                    <tr>
                        <td><strong>Last Login</strong></td>
                        <td>@Model.LastLogInDateTime.ToShortDateString()</td>
                    </tr>
                    <tr>
                        <td><strong>Update</strong></td>
                        <td><input type="submit" class="btn-sm btn-success" value="Update" /></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</form>

CoreBB.Web/CoreBB.Web/Views/User/Index.cshtml
@model IEnumerable<CoreBB.Web.Models.User>
@{
    ViewBag.Title = "Users";
}

<div class="container" style="margin-top:60px">
    <div class="card border-info">
        <div class="card-header text-white bg-info">
            <strong>Users</strong><span>&nbsp;-&nbsp;Total:@Model.Count()</span>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-striped table-hover">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Register</th>
                    <th>Last Login</th>
                    <th>Administrator</th>
                    <th>Locked</th>
                    <th>Operation</th>
                </tr>
                @foreach (var u in Model)
                {
                <tr>
                    <td>@u.Id</td>
                    <td><a asp-controller="User" asp-action="Detail" asp-route-name="@u.Name">@u.Name</a></td>
                    <td>@u.RegisterDateTime.ToShortDateString()</td>
                    <td>@u.LastLogInDateTime.ToShortDateString()</td>
                    <td><input type="checkbox" disabled="disabled" asp-for="@u.IsAdministrator" /></td>
                    <td><input type="checkbox" disabled="disabled" asp-for="@u.IsLocked" /></td>
                    <td><a class="btn-sm btn-primary" asp-controller="User" asp-action="Detail"
                          asp-route-name="@u.Name">
                        Detail
                        </a>
                    </td>
                </tr>
                }
            </table>
        </div>
    </div>
</div>

CoreBB.Web/CoreBB.Web/Views/User/LogIn.cshtml
@model CoreBB.Web.Models.LogInViewModel
@{
    ViewData["Title"] = "LogIn";
}

<div class="container col-4 offset-4", style="margin-top:120px">
    <div class="card border-info">
        <div class="card-header text-white bg-info">
            <strong>Login</strong>
        </div>
        <div class="card-body">
            <form asp-action="LogIn" method="post">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input class="form-control" asp-for="Name" />
                </div>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input class="form-control" asp-for="Password" type="password" />
                </div>
                <input type="submit" class="btn btn-primary float-right" value="Log In" />
            </form>
        </div>
    </div>
</div>

CoreBB.Web/CoreBB.Web/Views/User/Register.cshtml
@model  CoreBB.Web.Models.RegisterViewModel
@{
    ViewBag.Title = "Register";
}

<div class="container col-4 offset-4" style="margin-top:120px">
    <div class="card border-info">
        <div class="card-header text-white bg-info">
            <strong>Register</strong>
        </div>
        <div class="card-body">
            <form asp-action="Register" method="post">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input class="form-control" asp-for="Name" />
                </div>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input class="form-control" asp-for="Password" type="password" />
                </div>
                <div class="form-group">
                    <label asp-for="RepeatPassword"></label>
                    <input class="form-control" asp-for="RepeatPassword" type="password" />
                </div>
                <div class="form-group">
                    <label asp-for="Description"></label>
                    <textarea class="form-control" style="min-height:120px" asp-for="Description"></textarea>
                </div>
                <input type="submit" class="btn btn-primary float-right" value="Register" />
            </form>
        </div>
    </div>
</div>